import Image from "next/image";
import React from "react";
import { Button } from "flowbite-react";
import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Error-404",
  description: "Generated by create next app",
};
const Error = () => {
  return (
    <>
      <div className="h-screen flex items-center justify-center bg-white dark:bg-darkgray">
        <div className="text-center">
          <Image
            src={"/images/not-found.jpg"}
            width={600}
            height={400}
            alt="error"
            className="mb-4"
          />
          <h1 className="text-ld text-4xl mb-6"></h1>
          <h6 className="text-xl text-ld">
            لم يتم العثور على الصفحة التي تبحث عنها.
          </h6>
          <Button
            color={"primary"}
            as={Link}
            href="/"
            className="w-fit mt-6 mx-auto bg-primary-600 text-white hover:bg-primary-500"
          >
            العودة الى الرئيسية{" "}
          </Button>
        </div>
      </div>
    </>
  );
};

export default Error;
